//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortFol.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortFol.Resources.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt; ARREGLAR Y CONTINUAR.
        /// </summary>
        public static string BugFixButtonText {
            get {
                return ResourceManager.GetString("BugFixButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo en la inicialización de la variable de estado &apos;USER_INTENT&apos;. El sistema está detenido. Por favor, arregle el error para continuar..
        /// </summary>
        public static string BugMessage {
            get {
                return ResourceManager.GetString("BugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR CRÍTICO: KERNEL PANIC (0xF00D).
        /// </summary>
        public static string BugTitle {
            get {
                return ResourceManager.GetString("BugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [12:22:00] INICIANDO SECUENCIA DE ARRANQUE....
        /// </summary>
        public static string Intro_Line1_Connecting {
            get {
                return ResourceManager.GetString("Intro_Line1_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [12:22:01] VALIDACIÓN DE CREDENCIALES: OK..
        /// </summary>
        public static string Intro_Line2_AuthGranted {
            get {
                return ResourceManager.GetString("Intro_Line2_AuthGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [12:22:02] BUSCANDO ARCHIVO: ABOUT_ME.TXT....
        /// </summary>
        public static string Intro_Line3_SearchFile {
            get {
                return ResourceManager.GetString("Intro_Line3_SearchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [12:22:03] CARGA INICIAL COMPLETA. INYECTANDO MÓDULOS....
        /// </summary>
        public static string Intro_Line4_Loading {
            get {
                return ResourceManager.GetString("Intro_Line4_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [12:22:04] EJECUTANDO PORTFOLIO_GUI.EXE....
        /// </summary>
        public static string Intro_Line5_Executing {
            get {
                return ResourceManager.GetString("Intro_Line5_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estrategia / FODA.
        /// </summary>
        public static string Navbar_About {
            get {
                return ResourceManager.GetString("Navbar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto / Enlace.
        /// </summary>
        public static string Navbar_Contact {
            get {
                return ResourceManager.GetString("Navbar_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio / Boot.
        /// </summary>
        public static string Navbar_Home {
            get {
                return ResourceManager.GetString("Navbar_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos / Logs.
        /// </summary>
        public static string Navbar_Projects {
            get {
                return ResourceManager.GetString("Navbar_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Stack / System_Specs.
        /// </summary>
        public static string Navbar_Stack {
            get {
                return ResourceManager.GetString("Navbar_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, Desarrollador. Acceso Establecido..
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
